### PR TITLE
Fixed AZ CLI commands

### PR DESCRIPTION
**Pull request by benmcgarry**
Just a few command fixes as a few have been depreciated in the README.

### CODE REVIEW

**Review by ganrad — APPROVED** [review]
Good catch Ben.

**Review by ganrad — COMMENTED** [review]
az deployment create - Creates a deployment at the subscription scope.  There is no command 'az deployment group ....' in Az CLI v2.1+.

**Comment by benmcgarry** [comment]
In CLI 2.3+ it exists which is the latest stable (Released today)

https://docs.microsoft.com/en-us/cli/azure/deployment/group?view=azure-cli-latest

image

**Review by ganrad — APPROVED** [review]
Checked & verified the Az CLI commands work in v2.2+.  Thanks.

**Pull request merged**
